apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicaset
   namespace: namespace 
spec:
  replicas: 5
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9
